### ISSUE TITLE
Fish config

### ISSUE THREAD

**Issue by philn** [ricoriedel/wipe#1]
Bind ctrl-l to wipe using `bind \cl 'wipe --duration 1200; commandline -f repaint'` :)

**Comment by ricoriedel** [comment]
I will add a fish config file as soon as I have time.
Thank you for your contribution!

**Comment by ricoriedel** [comment]
I have added a config file at `misc/shell/wipe.fish`. The file is included in a new patch release. (I also upgraded some dependencies.)
Please close this issue, if it has been resolved.

**Comment by philn** [comment]
Thanks!
